version: '3.8'
services:
  postgres:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
